# Generated by Django 2.2.1 on 2019-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('why_wheelchair_friendly', models.TextField()),
                ('additional_information', models.TextField()),
                ('negative_filters', models.ManyToManyField(related_name='negative_filters', to='filters.Filter')),
                ('positive_filters', models.ManyToManyField(related_name='positive_filters', to='filters.Filter')),
            ],
        ),
    ]
