# Generated by Django 2.2.1 on 2019-05-14 18:18

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='gym/'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='additional_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='negative_filters',
            field=models.ManyToManyField(blank=True, related_name='negative_filters', to='filters.Filter'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='positive_filters',
            field=models.ManyToManyField(blank=True, related_name='positive_filters', to='filters.Filter'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='why_wheelchair_friendly',
            field=models.TextField(blank=True),
        ),
    ]
