# Generated by Django 2.2.1 on 2019-05-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('suggestions', '0003_suggestion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='negative_filters',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='positive_filters',
        ),
        migrations.AddField(
            model_name='suggestion',
            name='filters',
            field=models.ManyToManyField(blank=True, to='filters.Filter'),
        ),
    ]
