# Generated by Django 2.2.1 on 2019-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='contact_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='opening_hours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
