# Generated by Django 2.2.1 on 2019-05-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('gym', '0002_auto_20190513_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='additional_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='negative_filter',
            field=models.ManyToManyField(related_name='negative_filter', to='filters.Filter'),
        ),
        migrations.AddField(
            model_name='gym',
            name='positive_filter',
            field=models.ManyToManyField(related_name='positive_filter', to='filters.Filter'),
        ),
        migrations.AddField(
            model_name='gym',
            name='why_wheelchair_friendly',
            field=models.TextField(blank=True, null=True),
        ),
    ]
