# Generated by Django 2.2.1 on 2019-05-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('gym', '0003_auto_20190513_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='additional_information',
            new_name='about',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='why_wheelchair_friendly',
        ),
        migrations.AddField(
            model_name='gym',
            name='reviews',
            field=models.ManyToManyField(to='reviews.Review'),
        ),
    ]
