# Generated by Django 2.2.1 on 2019-05-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20190514_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='reviews.Review'),
        ),
    ]
