# Generated by Django 2.2.1 on 2019-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20190514_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='negative_filter',
            field=models.ManyToManyField(blank=True, to='filters.NegativeFilter'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='positive_filter',
            field=models.ManyToManyField(blank=True, to='filters.Filter'),
        ),
    ]
