# Generated by Django 2.2.1 on 2019-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20190514_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='slug',
            field=models.SlugField(default='Slug'),
            preserve_default=False,
        ),
    ]
